export const
    AUTH_USER = 'AUTH_USER',
    UNAUTH_USER = 'UNAUTH_USER',
    AUTH_ERROR = 'AUTH_ERROR',
    GET_ALL_IMAGES = 'GET_ALL_IMAGES',
    SET_SELECTED_IMAGE = 'SET_SELECTED_IMAGE',
    BAD_REQUEST = 'BAD_REQUEST',
    GET_ALL_USERS = 'GET_ALL_USERS',
    BLOCK_USER = 'BLOCK_USER',
    SET_ADMIN = 'SET_ADMIN',
    RESET_PASSWORD = 'RESET_PASSWORD';